data:
  name: leop_dec
  path: ./data/demo/dec
  transform:
    ligand_atom_mode: basic
    ligand_bond_mode: fc
    random_rot: False

model:
  checkpoint: ./ckpt/diffleop_dec.pt

affinity_predictor: use

sample:
  seed: 2024
  batch_size: 1
  num_samples: 2
  num_steps: 1000